name: Discord notifications


on:
  push:
    branches: 
      - master

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    
    steps:
      - name: Discord action notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Action called: {{ GITHUB_ACTION }} with {{ EVENT_PAYLOAD.action }}'
